apiVersion: v1
kind: PersistentVolume
metadata: 
  name: testpv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
   path: /data/mysql
   server: 10.10.12.108
